[package]
name = "blockchain"
version = "0.1.0"
authors = ["kikutea330 <kikutea330@openmailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
sha2 = "0.8"